# Generated by Django 3.0.12 on 2022-01-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('0', 'Administrator'), ('1', 'QVT'), ('2', 'Normal_user')], default='2', max_length=50),
        ),
    ]
