# Generated by Django 3.0.12 on 2022-01-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220120_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='comapny',
            new_name='company',
        ),
    ]
