# Generated by Django 3.1.1 on 2022-03-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Debit',
        ),
        migrations.DeleteModel(
            name='GiftCard',
        ),
    ]
